<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\build\Mod.props" />
  <PropertyGroup>
    <!-- 6 zeroes so we load before Gears: StrongMods replaces the XML patcher, so it must run first. -->
    <ModLoadPrefix>000000-</ModLoadPrefix>
  </PropertyGroup>
  <ItemGroup>
    <GameAssembly Include="Noemax.GZip" />
  </ItemGroup>
  <Import Project="..\build\Mod.targets" />
</Project>
